name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event,hhh]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: check type
        if: github.event.action == 'my-event'
        run: echo ${{ github.event.client_payload.sha }}
