name: create a repo dispatch event
on: 
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jwalton/gh-find-current-pr@v1
      if: github.event_name == 'push' 
      id: findPr
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    # This will cancel current push triggered workflow run, or be skipped if there is no current PR.
    - name: cancelling
      if: github.event_name == 'push' && steps.findPr.outputs.number 
      uses: andymckay/cancel-action@0.2
    - uses: actions/checkout@v2
    - run: echo hello 
     
