name: test bash
on: 
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jwalton/gh-find-current-pr@v1
      if: github.event_name == 'push' 
      id: findPr
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    # This will cancel current push triggered workflow run, or be skipped if there is no current PR.
    - name: cancelling
      if: github.event_name == 'push' && steps.findPr.outputs.number 
      uses: andymckay/cancel-action@0.2
    - run: sleep 5s
      if: github.event_name == 'push' && steps.findPr.outputs.number 
    - uses: actions/checkout@v2

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT" 
    - name: step hello
      run: |
        echo hello
        
    - name: create artifacts
      run: echo artifacts
      if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/devel' )



