name: create a repo dispatch event
on: 
  pull_request:
    paths-ignore: 
    - 'README.md'    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #ddd
    - uses: actions/checkout@v2
    - uses: harupy/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/workflows/tests.log
