name: test bash
on: 
  push:
    paths:
      - '23.txt' 
      - 'src/111/**.js'
  pull_request:
    paths:
      - '23.txt' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #ddd
    - uses: actions/checkout@v2
    - name: Check package version 
      run: |
        RELEASE_VERSION=2.3.1
        TAG_LIST=(`echo $RELEASE_VERSION | tr '.' ' '`)
        
    - name: Download all dependent repositories.
      id: setup
      run: echo hello
      if: steps.check.outcome == 'failure' || steps.check.outcome == 'success'


