name: create a repo dispatch event
on: 
  pull_request:
    branches:
      - develop 
jobs:
  skip-build:
    runs-on: ubuntu-latest
    steps:
    #ddd
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v2
    - name: Check package version 
      run: |
        manifest=$(curl -X GET https://docker.pkg.github.com/v2/zhuorg/dockertest/docker-example/manifests/5bcea215e75eb025458e145a117907a3556e98e3 -u $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }} | jq '.')
        echo $manifest
