name: create a repo dispatch event
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #ddd
    - uses: actions/checkout@v2
    - run: echo ${{github.run_id}}  
    - uses: actions/setup-java@1
      with:
        java-version: '11.0.5'
