name: test bash
on: 
  pull_request:


jobs:
  automerge:
    name: Merge Dependabot pull request
    runs-on: ubuntu-latest
    if: github.base_ref == 'master' && github.actor == 'zhu5201314'
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pullRequests.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })


