name: create a repo dispatch event
on: 
  pull_request:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      continue: ${{steps.changefile.outputs.continue}}
    steps:
    #ddd
    - uses: actions/checkout@v1
    - name: file changes 
      id: changefile 
      run: | 
        changed_file=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{github.event.after}})
        file_count=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{github.event.after}} | wc -l )
        if [[ $changed_file == '.github/workflows/former.yml' && $file_count == 1 ]]
        then 
          echo ::set-output name=continue::false
        else 
          echo ::set-output name=continue::true
        fi
  build:
     runs-on: ubuntu-latest
     needs: [check-changes]
     if: needs.check-changes.outputs.continue == 'false' 
     steps:
     - run: echo hello
       
