name: create a repo dispatch event
on: 
  pull_request:
    branches:
      - develop 
jobs:
  skip-build:
    runs-on: ubuntu-latest
    steps:
    #ddd
    - uses: actions/checkout@v2
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event) }}
      run: echo "$GITHUB_CONTEXT"

    - name: file changes 
      run: | 
        echo $(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{github.event.after}})
