name: test bash
on: 

  pull_request:


jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      continue: ${{steps.changefile.outputs.continue}}
    steps:
    #ddd

    - uses: actions/checkout@v2
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT" 
    - name: step hello
      run: |
        echo hello
        
    - name: create artifacts
      run: echo artifacts
      if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/devel' )



