name: test bash
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #ddd
    - uses: actions/checkout@v2
    - name: Check package version 
      run: |
        RELEASE_VERSION=2.3.1
        TAG_LIST=$(echo $RELEASE_VERSION | tr '.' ' ')

        # this will pass
        if [[ "${#TAG_LIST[@]}" -ne 3 ]]; then
          echo "$RELEASE_VERSION is not a valid semantic version"
          exit 1
        fi


        
