name: create a repo dispatch event
on: 
  pull_request:
    branches:
      - develop 
jobs:
  skip-build:
    runs-on: ubuntu-latest
    steps:
    #ddd
    - uses: actions/checkout@v1
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event) }}
      run: echo "$GITHUB_CONTEXT"

    - name: file changes 
      run: | 
        $changed_file=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{github.event.after}})
        $file_count=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{github.event.after}}) | wc -l
        if [[ $changed_file == '.github/workflows/former.yml' && $file_count == 1 ]]
        then 
          echo ::set-output name=continue::false
        else 
          echo ::set-output name=continue::true
        fi
