
name: Get new Unity license activation file
on:

    
  workflow_dispatch:
    inputs:
      puppy:
        description: 'A kind of puppy.'

        required: true

jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
    - run: echo hello
