name: Get file
on:  
  workflow_dispatch:
    inputs:
      newUnityVersion:
        description: 'The new version number string to generate the license activation file for.'
        required: true

jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
    - run: echo hello
