  
name: test manual trigger
on:  

  workflow_dispatch:
    inputs:
      newUnityVersion:
        description: 'The new version number string .'
        required: true

jobs:
  build:
    name: Request manual activation
    runs-on: ubuntu-latest
    steps:
    - run: echo hello
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
