  
name: test manual trigger
on:  
  push:
    paths: 
      - '.github/workflows/testmanual.yaml'

jobs:
  build:
    name: 114e
    runs-on: ubuntu-latest
    steps:
    - run: echo hello
    - name: Dump GitHub context
      run: |
         echo $GITHUB_JOB 
      env: 
        var1: ${{job.status}}
