  
name: test manual trigger
on:  
  push:
    paths: 
      - '.github/workflows/testmanual.yaml'

jobs:
  build:
    name: Request manual activation
    runs-on: ubuntu-latest
    steps:
    - run: echo hello
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
         echo "$GITHUB_CONTEXT"
         echo $GITHUB_JOB 
